### PR TITLE
Some tweaks for bamboo support

### PR DESCRIPTION
**Pull request by martinrakovec**

### CODE REVIEW

**Comment by sysradium** [comment]
Can you take a look at why tests are failing?

**Comment by martinrakovec** [comment]
It should be OK now. I did some change in behavior that was why tests failed. I added an optional argument for TestCase to enable new behavior (multiple error/failure/skipped sub-elements).

**Comment by martinrakovec** [comment]
Is there any chance to close this pull request @sysradium? It seems tests are OK now.

**Comment by sysradium** [comment]
Well, it's still failing for at least python 3.3

**Comment by martinrakovec** [comment]
The checks are failing probably because of unsupported interpreter "py33: InterpreterNotFound: python3.3". I do not understand how this works or which interpreters are supported. But it seems I did not break this by changes. Is there any possibility to run this check on the master branch to check if it is working? Then we could disable the checks for failing interprets

**Comment by sysradium** [comment]
Good question. I need to have a look 🤔

**Comment by sysradium** [comment]
@martinrakovec I think now you can fix the merge conflicts and it'll just work.

**Comment by martinrakovec** [comment]
@sysradium Is there any chance that this changes will make it to PyPi?

**Pull request merged**
